# Generated by Django 4.2 on 2023-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_ratings_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article_images'),
        ),
    ]
