# Generated by Django 4.2.1 on 2024-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_image_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
